train_data_path: "data/dbpedia/train_subset.jsonl"
test_data_path: "data/dbpedia/dev_subsample.jsonl"
tokenizer_path: "distilgpt2"
n_shot: 1
label_mapping: {'1': 'company', '2': 'school', '3': 'artist', '4': 'athlete', '5': 'politics', '6': 'transportation', '7': 'building', '8': 'nature', '9': 'village', '10': 'animal', '11': 'plant', '12': 'album', '13': 'film', '14': 'book'}
corpus_params: {'sentence_1_str': 'sentence', 'label_str': 'label'}
template: "f'input: {sentence_1}\\ntype: {label_text}\\n\\n'"
sample_mode: "balance"
sentence_pair: False
permutation_max_size: 24
