train_data_path: "data/rte/train.jsonl"
test_data_path: "data/rte/dev.jsonl"
tokenizer_path: "distilgpt2"
n_shot: 8
label_mapping: {'not_entailment': 'False', 'entailment': 'True'}
corpus_params: {'sentence_1_str': 'sentence_1', 'sentence_2_str': 'sentence_2', 'label_str': 'label'}
template: "f'premise: {sentence_1}\\nhypothesis: {sentence_2}\\nprediction: {label_text}\\n\\n'"
sample_mode: "balance"
sentence_pair: True
permutation_max_size: 24
