train_data_path: "data/sst5/train.jsonl"
test_data_path: "data/sst5/dev_subsample.jsonl"
tokenizer_path: "distilgpt2"
n_shot: 1
label_mapping: {'0': 'terrible', '1': 'bad', '2': 'okay', '3': 'good', '4': 'great'}
corpus_params: {'sentence_1_str': 'sentence', 'label_str': 'label'}
template: "f'Review: {sentence_1}\\nSentiment: {label_text}\\n\\n'"
sample_mode: "balance"
sentence_pair: False
permutation_max_size: 24
