train_data_path: "data/trec/train.jsonl"
test_data_path: "data/trec/dev_subsample.jsonl"
tokenizer_path: "distilgpt2"
n_shot: 1
label_mapping: {'0': 'description', '1': 'entity', '2': 'expression', '3': 'human','4': 'location', '5': 'number'}
corpus_params: {'sentence_1_str': 'sentence', 'label_str': 'label'}
template: "f'Question: {sentence_1}\\nType: {label_text}\\n\\n'"
sample_mode: "balance"
sentence_pair: False
permutation_max_size: 24
